### PR TITLE
Make primary key name as parameter

### PR DESCRIPTION
**Pull request by ZAYEC77**

### CODE REVIEW

**Comment by arisk** [comment]
Can you explain the purpose of this? If you want to use a different primary key all you need to do is override `primaryKey()` from the active record class in your model.

**Comment by ZAYEC77** [comment]
In my case, I have find model by field which is not primary key.

**Comment by arisk** [comment]
Can you change `$model->__get($this->primaryKey)` to `$model->{$this->primaryKey}`?

**Comment by ZAYEC77** [comment]
yeah, sure. Please, look now

**Comment by arisk** [comment]
Thank you!

**Pull request merged**
